// Bundles the in-page TypeScript into a single script that ZenticKit injects
// via WKUserScript.
//
// Output is committed to the repo so an Xcode build never requires Node. Run
// `npm run build` after changing anything under src/ and commit the result.

import { build, context } from "esbuild";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const outfile = join(here, "..", "Sources", "ZenticKit", "Resources", "zentic.js");
const version = JSON.parse(readFileSync(join(here, "package.json"), "utf8")).version;

/** @type {import("esbuild").BuildOptions} */
const options = {
  entryPoints: [join(here, "src", "main.ts")],
  outfile,
  bundle: true,
  // An IIFE, because this is injected as a script body rather than imported.
  format: "iife",
  // WKWebView on macOS 26 / iOS 26. No transpilation tax for syntax the engine
  // already has, and no polyfills to ship.
  target: ["safari18"],
  platform: "browser",
  // Kept readable: this script runs inside other people's pages, and when
  // something goes wrong the stack trace needs to be legible in Web Inspector.
  minify: false,
  sourcemap: false,
  legalComments: "none",
  alias: {
    // KaTeX's own minified build, not its source. This script is injected into
    // every page, and the readable build is 620KB of vendored parser tables that
    // nobody is going to read in Web Inspector — our code stays legible, the
    // vendor code does not need to be. Same public API either way.
    katex: "katex/dist/katex.min.js",
  },
  define: {
    __ZENTIC_VERSION__: JSON.stringify(version),
  },
  banner: {
    js: "/* Zentic in-page bundle — generated by web/build.mjs. Do not edit. */",
  },
  logLevel: "info",
};

if (process.argv.includes("--watch")) {
  const ctx = await context(options);
  await ctx.watch();
  console.log("watching web/src -> " + outfile);
} else {
  await build(options);
  console.log("built " + outfile);
}
