// Bundles the in-page TypeScript into the scripts that ZenticKit injects.
//
// Two of them, and the split is the point:
//
//   zentic.js              — every navigation in every tab, via WKUserScript at
//                            document-start.
//   zentic-lens-editor.js  — only when the user presses ⌥⌘L, via
//                            `ReaderBridge.deliverLensEditor(to:)`, into the same
//                            `zentic` content world.
//
// The editor is 59KB that cannot run until that keystroke, so it does not belong
// in the script the other 99% of pageviews parse. See `src/lens/deferred.ts`.
//
// Output is committed to the repo so an Xcode build never requires Node. Run
// `npm run build` after changing anything under src/ and commit the result.

import { build, context } from "esbuild";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const resources = join(here, "..", "Sources", "ZenticKit", "Resources");
const version = JSON.parse(readFileSync(join(here, "package.json"), "utf8")).version;

/**
 * @param {string[]} entry Path segments under `src/`.
 * @param {string} name Resource file name.
 * @returns {import("esbuild").BuildOptions}
 */
function bundle(entry, name) {
  return {
    entryPoints: [join(here, "src", ...entry)],
    outfile: join(resources, name),
    bundle: true,
    // An IIFE, because this is injected as a script body rather than imported.
    format: "iife",
    // WKWebView on macOS 26 / iOS 26. No transpilation tax for syntax the engine
    // already has, and no polyfills to ship.
    target: ["safari18"],
    platform: "browser",
    // Whitespace only. Every identifier, class and function name survives, so a
    // Web Inspector stack trace still reads `LensEngine.runPass`, `console.info`
    // still names our own symbols, and `error.stack` posted back over the bridge
    // still says which stage failed. What is lost is line and column numbers —
    // the whole bundle is a handful of very long lines, so a trace points at the
    // right function and not at the right line inside it.
    //
    // That trade was taken because this script is parsed on every navigation in
    // every tab, and the readable build costs 398KB and ~1.7ms of V8 compile on
    // each one. Debugging with a named frame and no line number is a mild
    // inconvenience for us; a third of a megabyte is a real cost for the user, on
    // every page they open. If a line number is ever genuinely needed, flip this
    // off locally — nothing about the code depends on it.
    minify: false,
    minifyWhitespace: true,
    sourcemap: false,
    legalComments: "none",
    alias: {
      // KaTeX's own minified build, not its source. The readable build is 620KB
      // of vendored parser tables that nobody is going to read in Web Inspector.
      // Same public API either way.
      katex: "katex/dist/katex.min.js",
    },
    define: {
      __ZENTIC_VERSION__: JSON.stringify(version),
    },
    banner: {
      js: "/* Zentic in-page bundle — generated by web/build.mjs. Do not edit. */",
    },
    logLevel: "info",
  };
}

/** Both bundles, in injection order. Exported so the bundle test can build the
 * real configuration rather than a plausible-looking copy of it. */
export const bundles = [
  bundle(["main.ts"], "zentic.js"),
  bundle(["lens", "editor-entry.ts"], "zentic-lens-editor.js"),
];

// Importing this file must not write to Resources — the test does exactly that.
const invokedDirectly =
  process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) {
  if (process.argv.includes("--watch")) {
    for (const options of bundles) {
      const ctx = await context(options);
      await ctx.watch();
      console.log("watching web/src -> " + options.outfile);
    }
  } else {
    for (const options of bundles) {
      await build(options);
      console.log("built " + options.outfile);
    }
  }
}
